name: Rodar ETL Diário

on:
  schedule:
    # Roda às 09h, 11h e 14h (Horário de Brasília)
    # 12 = 09h BRT | 14 = 11h BRT | 17 = 14h BRT
    - cron: '0 12,14,17 * * 1-5' 
  workflow_dispatch:      # Permite rodar manualmente a qualquer momento

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Necessário para salvar o banco de dados no repositório
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Playwright e Dependências de Sistema
        run: playwright install chromium --with-deps

      - name: Executar Script ETL
        run: python main_etl.py
        env:
          PYTHONPATH: .

      - name: Salvar Dados no Repositório (Git Push)
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add data/*.db
          # O commit só acontece se houver alteração real no banco
          git commit -m "Auto-update DB: $(date +'%d/%m/%Y %H:%M')" || echo "Sem mudanças para salvar"
          git push
